listen: ":25565"
domains:
  - domain: "sample0.test.com"
    ip: "192.168.1.10"
    port: 25565
    allowed_ips:   # このドメインへのアクセス許可IP（省略可）
      - "127.0.0.1"
      - "192.168.1.100"
  - domain: "sample1.test.com"
    ip: "192.168.1.11"
    port: 25566
    # allowed_ips: を省略すると全許可

allowed_ips: # 全体のアクセス許可IP（省略可）
  - "127.0.0.1"
  - "192.168.1.200"